baseURL = "http://example.org/"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]
title = "John Paul Shen, MD"

[params]
  description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
  logo = "fa-diamond"
  copyright = "John Paul Shen, MD & Huwate 'Kwat' Yeerna"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "#"
